---
- hosts: all
  become: yes
  tasks:
  - name: install jdk on ubuntu20 node1
    apt:
     name: "{{myjavaonubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install jdk8 on amazonlinux2 node2
    yum:
     name: "{{myjavaonamazonlinux2}}"
     state: present
    when: ansible_os_family =="RedHat"